# Generated by Django 2.1.5 on 2019-02-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_open_hours_start', models.CharField(max_length=10)),
                ('company_open_hours_end', models.CharField(max_length=10)),
                ('company_open_days_start', models.CharField(max_length=3)),
                ('company_open_days_end', models.CharField(max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactus.Company')),
            ],
        ),
    ]
