# Generated by Django 2.1.5 on 2019-02-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_companyhq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhq',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactus.Company'),
        ),
    ]
