# Generated by Django 2.1.5 on 2019-02-26 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0006_auto_20190226_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.CharField(max_length=100)),
                ('customer_phone_number', models.CharField(max_length=100)),
                ('customer_subject', models.CharField(max_length=200)),
                ('customer_text', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='companyhq',
            options={'verbose_name_plural': 'Company HQ info'},
        ),
        migrations.AlterModelOptions(
            name='customerservicehours',
            options={'verbose_name_plural': 'Customer Service Hours'},
        ),
        migrations.AddField(
            model_name='message',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactus.Company'),
        ),
    ]
