# Generated by Django 2.1.5 on 2019-02-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20190228_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.Table'),
        ),
    ]
