# Generated by Django 2.1.5 on 2019-02-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20190228_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_type',
            field=models.IntegerField(),
        ),
    ]
