# Generated by Django 2.1.5 on 2019-03-11 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservationdatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdatabase',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.Reservation'),
        ),
        migrations.AlterField(
            model_name='reservationdatabase',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.Table'),
        ),
    ]
