# Generated by Django 2.1.5 on 2019-03-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_auto_20190311_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
